### PR TITLE
Readme: Add reference to NixOS package

### PR DESCRIPTION
**Pull request by erikarvstedt**

### CODE REVIEW

**Comment by brandon-dacrib** [comment]
travis was not configured when you committed this, I don't see how to re-run an old travis job so I suggest doing a pull and pushing this again and when it passes the CI, I will merge it.

**Comment by erikarvstedt** [comment]
Rebased to master.

**Comment by brandon-dacrib** [comment]
you closed this, did you intend for me to merge it?

**Comment by erikarvstedt** [comment]
Sorry, please wait a second.

**Comment by erikarvstedt** [comment]
Can't reopen this PR, created a new one.

**Pull request closed without merging**
